all : ../index.html ../suggested.html ../past.html ../gradop.html

../index.html : index.md
	markdown index.md > ../index.html

../suggested.html : suggested.md
	markdown suggested.md > ../suggested.html

../past.html : past.md
	markdown past.md > ../past.html

../gradop.html : gradop.md
	markdown gradop.md > ../gradop.html
